# Platform templates
#
# Used to provide base for multi-arch runs. Each platform can be globally
# disabled with `PLATFORM_LINUX_...` variable. Some targets have pre-defined
# `QEMU_CPU`, which is either the only or the default QEMU configuration for a
# given platform.

.platform:all:
  rules:
    - if: "$PLATFORM =~ $ACTIVE_CODE_PATTERN"
  image:
    name: $DOCKER_IMAGE_NAME-$PLATFORM

# i386 is used for `mmx`, `sse2` and `ssse3` backend tests.
.platform:linux:386:
  extends: .platform:all
  # Waiting for https://gitlab.com/gitlab-org/gitlab/-/issues/423553
  needs:
    - job: docker-codecov
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux-386
  variables:
    PLATFORM: linux-386

# amd64 is used for general tests.
.platform:linux:amd64:
  extends: .platform:all
  needs:
    - job: docker-codecov
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux-amd64
  variables:
    PLATFORM: linux-amd64

# ARMv5 is used for `arm-simd` test.
.platform:linux:arm:v5:
  extends: .platform:all
  needs:
    - job: docker-codecov
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux-arm-v5
  variables:
    PLATFORM: linux-arm-v5
    # It is in fact an ARMv6 CPU, which is required for SIMD to get discovered
    # on runtime.
    QEMU_CPU: arm1136

# ARMv7 is used for ARMv7 variant of `arm-neon`.
.platform:linux:arm:v7:
  extends: .platform:all
  needs:
    - job: docker-codecov
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux-arm-v7
  variables:
    PLATFORM: linux-arm-v7

# ARM64v8 is used for `arm-neon`.
.platform:linux:arm64:v8:
  extends: .platform:all
  needs:
    - job: docker-codecov
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux-arm64-v8
  variables:
    PLATFORM: linux-arm64-v8

# MIPS64EL used for `loongson-mmi`.
.platform:linux:mips64el:
  extends: .platform:all
  needs:
    - job: docker-codecov
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux-mips64el
  variables:
    PLATFORM: linux-mips64el
    QEMU_CPU: "Loongson-3A4000"

# MIPS (32 bit, little endian) is used for `mips-dspr2`.
.platform:linux:mipsel:
  extends: .platform:all
  needs:
    - job: docker-codecov
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux-mipsel
  variables:
    PLATFORM: linux-mipsel
    # As written in the code comment, it's the only supported CPU.
    QEMU_CPU: 74Kf

# PPC64LE used for `vmx`.
.platform:linux:ppc64le:
  extends: .platform:all
  needs:
    - job: docker-codecov
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux-ppc64le
  variables:
    PLATFORM: linux-ppc64le

# RISCV64 used for `rvv`.
.platform:linux:riscv64:
  extends: .platform:all
  needs:
    - job: docker-codecov
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux-riscv64
  variables:
    PLATFORM: linux-riscv64
    QEMU_CPU: rv64,v=true,vext_spec=v1.0,vlen=256,elen=64
