# Platform templates
#
# Used to provide base for multi-arch runs. Each platform can be globally
# disabled with `PLATFORM_LINUX_...` variable. Some targets have pre-defined
# `QEMU_CPU`, which is either the only or the default QEMU configuration for a
# given platform.

# i386 is used for `mmx`, `sse2` and `ssse3` backend tests.
.platform:linux:386:
  needs:
    - job: docker-pixman
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux/386
  rules:
    - if: $PLATFORM_LINUX_386 == "true"
  image:
    name: $DOCKER_IMAGE_NAME-linux-386
    docker:
      platform: linux/386

# amd64 is used for general tests.
.platform:linux:amd64:
  needs:
    - job: docker-pixman
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux/amd64
  rules:
    - if: $PLATFORM_LINUX_AMD64 == "true"
  image:
    name: $DOCKER_IMAGE_NAME-linux-amd64
    docker:
      platform: linux/amd64

# ARMv5 is used for `arm-simd` test.
.platform:linux:arm:v5:
  needs:
    - job: docker-pixman
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux/arm/v5
  rules:
    - if: $PLATFORM_LINUX_ARM_V5 == "true"
  image:
    name: $DOCKER_IMAGE_NAME-linux-arm-v5
    docker:
      platform: linux/arm/v5
  variables:
    # It is in fact an ARMv6 CPU, which is required for SIMD to get discovered
    # on runtime.
    QEMU_CPU: arm1136

# ARMv7 is used for ARMv7 variant of `arm-neon`.
.platform:linux:arm:v7:
  needs:
    - job: docker-pixman
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux/arm/v7
  rules:
    - if: $PLATFORM_LINUX_ARM_V7 == "true"
  image:
    name: $DOCKER_IMAGE_NAME-linux-arm-v7
    docker:
      platform: linux/arm/v7

# ARM64v8 is used for `arm-neon`.
.platform:linux:arm64:v8:
  needs:
    - job: docker-pixman
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux/arm64/v8
  rules:
    - if: $PLATFORM_LINUX_ARM64_V8 == "true"
  image:
    name: $DOCKER_IMAGE_NAME-linux-arm64-v8
    docker:
      platform: linux/arm64/v8

# MIPS64EL used for `loongson-mmi`.
.platform:linux:mips64el:
  needs:
    - job: docker-pixman
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux/mips64el
  rules:
    - if: $PLATFORM_LINUX_MIPS64EL == "true"
  image:
    name: $DOCKER_IMAGE_NAME-linux-mips64el
    docker:
      platform: linux/mips64el
  variables:
    QEMU_CPU: "Loongson-3A4000"

# MIPS (32 bit, little endian) is used for `mips-dspr2`.
.platform:linux:mipsel:
  needs:
    - job: docker-pixman
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux/mipsel
  rules:
    - if: $PLATFORM_LINUX_MIPSEL == "true"
  image:
    name: $DOCKER_IMAGE_NAME-linux-mipsel
    docker:
      platform: linux/mipsel
  variables:
    # As written in the code comment, it's the only supported CPU.
    QEMU_CPU: 74Kf

# PPC64LE used for `vmx`.
.platform:linux:ppc64le:
  needs:
    - job: docker-pixman
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux/ppc64le
  rules:
    - if: $PLATFORM_LINUX_PPC64LE == "true"
  image:
    name: $DOCKER_IMAGE_NAME-linux-ppc64le
    docker:
      platform: linux/ppc64le

# RISCV64 used for `rvv`.
.platform:linux:riscv64:
  needs:
    - job: docker-pixman
      optional: true
      parallel:
        matrix:
          - PLATFORM: linux/riscv64
  rules:
    - if: $PLATFORM_LINUX_RISCV64 == "true"
  image:
    name: $DOCKER_IMAGE_NAME-linux-riscv64
    docker:
      platform: linux/riscv64
  variables:
    QEMU_CPU: rv64,v=true,vext_spec=v1.0,vlen=256,elen=64
